name: Ice Build CI

on:
  push:
    branches: [ main, fix/integration-test ]
  pull_request:
    branches: [ main, fix/integration-test ]

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30 # Prevent hangs from running indefinitely
    strategy:
      matrix:
        node-version: [22.x] # Test against Node.js versions
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false # Continue with other matrix combinations if one fails

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required for nx affected commands and git tag history

    - name: Fetch main branch
      run: git fetch origin main:main || echo "Main branch not found, will run all tests"
      shell: bash
      continue-on-error: true

    - name: System info
      run: |
        echo "OS: ${{ runner.os }}"
        echo "Node: ${{ matrix.node-version }}"
        if [ "$RUNNER_OS" = "Windows" ]; then
          echo "CPU Cores: $NUMBER_OF_PROCESSORS"
        elif [ "$RUNNER_OS" = "Linux" ]; then
          echo "CPU Cores: $(nproc)"
        elif [ "$RUNNER_OS" = "macOS" ]; then
          echo "CPU Cores: $(sysctl -n hw.ncpu)"
        fi
        echo "Memory: $(node -e 'console.log(Math.round(require("os").totalmem() / (1024 * 1024 * 1024)) + "GB")')"
      shell: bash

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Remove package-lock.json files (Windows)
      if: runner.os == 'Windows'
      run: |
        Get-ChildItem -Path . -Filter "package-lock.json" -Recurse | Remove-Item -Force
      shell: pwsh

    - name: Remove package-lock.json files (Unix)
      if: runner.os != 'Windows'
      run: |
        find . -name "package-lock.json" -type f -exec rm -f {} \;
      shell: bash

    - name: Install dependencies
      run: npm install
      timeout-minutes: 10

    # Replace the separate test commands with the simple command that works locally
    - name: Run tests (same as local environment)
      run: npm run test
      timeout-minutes: 15
      env:
        CI_PLATFORM: ${{ runner.os }}
        NODE_OPTIONS: --max-old-space-size=4096
      
    # Run additional tests only if the main tests succeed
    - name: Run Linting
      if: success() # Only run if tests passed
      run: npx nx run-many --target=lint --all
      continue-on-error: true

    - name: Build all packages
      if: success() # Only build if tests passed
      run: npm run build
      timeout-minutes: 15
      env:
        NODE_OPTIONS: --max-old-space-size=4096

    - name: Run Integration Tests (ice-build)
      if: success() # Only run if previous steps succeeded
      run: npm run test:integration --workspace=@n8d/ice-build
      timeout-minutes: 10
      env:
        CI_PLATFORM: ${{ runner.os }}
        DEBUG: "ice:*"

    - name: Run Integration Tests (ice-hotreloader)
      if: success() # Only run if previous steps succeeded
      run: npm run test:integration --workspace=@n8d/ice-hotreloader
      timeout-minutes: 10
      env:
        CI_PLATFORM: ${{ runner.os }}
        DEBUG: "ice:*"

    - name: Upload test logs
      if: always() # Run even if previous steps failed
      uses: actions/upload-artifact@v4
      with:
        name: test-logs-${{ matrix.os }}-node-${{ matrix.node-version }}
        path: |
          **/test-results
          **/junit.xml
          **/npm-debug.log*
          **/lerna-debug.log*
          **/yarn-debug.log*
          **/yarn-error.log*
        retention-days: 7

