name: Ice Build CI

on:
  push:
    branches: [ main, winfix ] # Adjust branches as needed
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x] # Test against Node 20
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies (using npm ci for workspaces)
      run: npm ci # Installs dependencies for all workspaces

    # Optional: Add linting step
    # - name: Lint ice-build
    #   run: npm run lint --workspace=@n8d/ice-build

    - name: Run Unit Tests (ice-build)
      run: npm run test --workspace=@n8d/ice-build # Assumes 'test' script runs vitest

    # --->>> ADD THIS BUILD STEP <<<---
    - name: Build ice package
      run: npm run build
      
    # Update integration test step to be platform-aware
    - name: Run Integration Tests (ice-build)
      run: npm run test:integration --workspace=@n8d/ice-build
      env:
        # Add environment variable to help the test script detect the platform
        CI_PLATFORM: ${{ runner.os }}
      
    # Add a Windows-specific post-check step
    - name: Verify Windows Compatibility
      if: runner.os == 'Windows'
      run: |
        echo "Verifying Windows-specific functionality..."
        # Add any Windows-specific checks if needed
