name: Clean up old workflow runs

on:
  workflow_dispatch: # This allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 UTC every Sunday

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 14
          keep_minimum_runs: 6
